# Site settings
title: David Raab's Digital Resume
description: David Raab's blog
favicon: /assets/images/favicon.ico
baseurl: http://www.davidraab.me
url: http://www.davidraab.me

# Build settings
markdown: kramdown

# Author settings
author:
  name: David Raab
  title: Student at Rensselaer Polytechnic Institute
  address: Hanover, Massachusetts
  email: davidfraab@gmail.com
  link: http://davidraab.me
  facebook: david.raab1
  github: draab
  linkedin: draab
  twitter: draab4life
  gavatar: assets/img/avatar.JPG
  workHistory:
    - work1:
      company: Rensselaer Student Union
      location: Troy, New York
      title: Junior Systems Administrator
      started: 2015
      duration: (September 2015 - present)
      description: I maintain software and support the student clubs and student union staff. I work with a team of other student employees and the Rensselaer Division of the Chief Information Officer in order to optimize the technical operations of the Rensselaer Union.
    - work2:
      company: IGS Systems
      location: Plymouth, Massachusetts
      title: Assistant to the Director of Engineering
      started: 2015
      duration: (June 2015 - August 2015)
      description: I processed computer equipment including iPads and MacBooks as they came into the warehouse and inventoried them in a spreadsheet. I packaged items and shipped them out of the warehouse as orders were placed.
  educationHistory:
    - education1:
      organization: Rensselaer Polytechnic Institute
      degree: Bachelor of Science
      major: Electrical Engineering
      started: 2015
      duration: (2015 - 2019)
      description: I am attending classes RPI and also getting involved in the plethora of activties that are always happening on campus. My current class schedule includes Calculus 2, Physics 2, Computer Science 1, and Democracy. 
    - education2:
      organization: Hanover High School
      degree: High School Diploma
      started: 2011
      duration: (2015-2019)
      description: I attended high school at Hanover High School in Hanover, MA. I was the valedictorian of my graduating class and participated in many extracirricular clubs and activties. These activities include Robotics, Band, Newspaper, and National Honor Society.
  extracirricularExperience:
    - club1:
      organization: RPI Senate Web Technologies Group
      duration: (September to present)
      description: They maintain open source projects for students of RPI to use. My main project as of the moment is to create an electronic voting system for the Student Senate to use during meetings and eventually for students to use during GM week elections every spring.
    - club1:
      organization: The Rensselaer Polytechnic
      duration: (September 2015 to present)
      leadership: Associate News Editor (September 2015 to present)
      description: <i>The Polytechnic</i> is the student newspaper reporting on events around the campus of Rensselaer Polytechnic Institute. As Associate News Editor, I am repsonsible for helping to layout the news section and reporting in interesting stories for weekly publication on Tuesday.
    - club2:
      organization: RPI Pep Band
      duration: (September 2015 to present)
      description: Pep Band is a group that performs at RPI Football and Hockey games in order to increase school spirit and get the crowd amped every week.
    - club3: 
      organization: National Honor Society
      duration: (November 2013 - June 2015)
      description: I was inducted to Hanover's chapter of the National Honor Society because I satisified requirements pretaining to grade point average, community service hours, leadership experience, and positive character.
      leadership: Treasurer (June 2014 - June 2015)
    - club4:
      organization: The HHS Indian
      leadership: Editor in Chief (September 2014 - June 2015)<br />Web Editor (September 2013 - September 2014)
      duration: (September 2013 - June 2015)
      description: The Indian is the student news club of Hanover High School. I joined the club right when it started and helped to establish their main web presence which exists to this day. Eventually, I became Editor in Chief which mean I was responsible for running all aspects of the club along with the faculty advisor.
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: AutoCAD and Autodesk Inventor
      proficiency: Intermediate
    - skill2:
      name: HTML/CSS
      proficiency: Intermediate
    - skill3:
      name: Java
      proficiency: Intermediate     
    - skill4:
      name: Python
      proficiency: Intermediate
    - skill5:
      name: C
      proficiency: Amateur
    - skill6:
      name: Linux Server Administration
      proficiency: Weekend Warrior