# Site settings
title:       David Raab
email:       davidraab@outlook.com
author:      David Raab
description: "The personal portfolio and landing page of David Raab."
baseurl:     ""
url:         "http://www.davidraab.me"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: draab
stackoverflow_id:
twitter_username: draab4life
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
