# Site settings
title: David Raab's Digital Resume
description: David Raab's blog
favicon: /iCard-Resume/assets/img/avatar.JPG
baseurl: http://www.davidraab.me
url: http://www.davidraab.me

# Build settings
markdown: kramdown

# Author settings
author:
  name: David Raab
  title: Student at Rensselaer Polytechnic Institute
  address: Hanover, Massachusetts
  email: davidfraab@gmail.com
  link: http://davidraab.me
  facebook: david.raab1
  github: draab
  linkedin: draab
  twitter: draab4life
  gavatar: assets/img/avatar.JPG
  workHistory:
    - work1:
      company: Rensselaer Student Union
      location: Troy, New York
      title: Junior Systems Administrator
      started: 2015
      duration: (September 2015 - present)
      description: I maintain software and support the student clubs and student union staff. I work with a team of other student employees and the Rensselaer Division of the Chief Information Officer in order to optimize the technical operations of the Rensselaer Union.
    - work2:
      company: IGS Systems
      location: Plymouth, Massachusetts
      title: Assistant to the Director of Engineering
      started: 2015
      duration: (June 2015 - August 2015)
      description: I processed computer equipment including iPads and MacBooks as they came into the warehouse and inventoried them in a spreadsheet. I packaged items and shipped them out of the warehouse as orders were placed.
  educationHistory:
    - education1:
      organization: Rensselaer Polytechnic Institute
      degree: Bachelor of Science
      major: Electrical Engineering
      started: 2015
      duration: (2015 - 2019)
      description: My Undergrate Education. Will include details in the course I've taken here.
    - education2:
      organization: Hanover High School
      degree: High School Diploma
      started: 2011
      duration: (2015-2019)
      description: High School Education. Include more information here!
  languages:
    - language1:
      name: English Proficient
      proficiency: Native
    - language2:
      name: French
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 80%
    - skill5:
      name: Java/Java EE
      percentage: 90%
