# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               David Raab
tagline:             'Personal blog'
description:         'The landing page and personal website of draab!'
url:                 http://wwww.davidraab.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
#version:             1.0.0
